# Generated by Django 5.2.6 on 2025-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='reader',
            unique_together={('reference_id', 'reader_name')},
        ),
    ]
