# Generated by Django 5.2.6 on 2025-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
