# Generated by Django 5.2.6 on 2025-09-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_borrowing_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
