# Generated by Django 5.2.6 on 2025-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_alter_reader_reader_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reader',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
