# Generated by Django 5.2.6 on 2025-09-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_borrowing_returned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='returned_date',
        ),
    ]
