# Generated by Django 5.2.6 on 2025-09-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
